### ISSUE TITLE
When playing with English language audio, no video appears

### ISSUE THREAD

**Issue by smartperson** [AddonScriptorDE/plugin.video.southpark_de#1]
Using a raspbmc build.
If I switch the language to German audio, then video appears fine.
Using version 1.0.2…

**Comment by ghost** [comment]
How / where do you switch the language?

**Comment by smartperson** [comment]
I switch the language by going to "Home/Settings/Addons/Installed/Southpark.de/Configure" There there is a toggle to switch between German and English for the language. Is there a step that I'm missing?

**Comment by ghost** [comment]
I don't have the "Configure" option, I only see the seasons and "play random". But I managed to get them in English by changing the value in the settings.xml file on my pi.

**Comment by smartperson** [comment]
I'll be back in my apartment on Sunday - when I get home I'll look at exactly the way my menus are laid out. I was able to configure it under the global settings menu from the home screen, there is a section of the config screen that is devoted to add-ons. If I can I'll attach screen shots.

**Comment by ghost** [comment]
I found it now, it is in the "global" settings. Kind of weird not to be able to access this from within the add-on itself. Watching with English audio works fine now. Thanks.

**Comment by smartperson** [comment]
Wait, so you get video when you watch in English? What are the contents of your settings.xml??

**Comment by ghost** [comment]
My settings.xml ( `/.xbmc/addons/plugin.video.southpark_de/resources/settings.xml` ) contains the following:

``` xml
<settings>
   <setting id="language" type="enum" label="30101" values="de|en" default="1"/>
   <setting id="playIntro" type="bool" label="30104" default="false"/>
   <setting id="forceViewMode" type="bool" label="30102" default="false"/>
   <setting id="viewMode" type="number" label="30103" default="500"/>
</settings>
```

I've only changed the `default="0"` in line 2 to `default="1"`

**Comment by ghost** [comment]
I have the same problem as @smartperson, cannot see any videos while switched to the en version. I am running xbmc on raspbmc (raspberry pi hardware).

**Comment by sharepass11** [comment]
The problem is that apparently some English videos are .flv instead of .mp4 . Which means they wont work with raspbmc. The newest episodes seem to be all in .mp4, so they work. On regular xbmc you can play .flv anyway. Its just that on the pi you can't.
I tried it by forcing it to use .mp4 always and it gave me an error on the English version that it didn't find the video, thus I assume the English version would be .flv.

**Comment by ghost** [comment]
Thanks for explanation, it seems you are absolutely correct.

**Comment by AddonScriptorDE** [comment]
Yes, like sharepass11 already said, its a problem with the codec:
RaspBMC still has problems with some codecs: http://forum.stmlabs.com/showthread.php?tid=1165
@youRFate: You can access the settings, like in any other addon, via the context menu "Addon-Settings".
