### ISSUE TITLE
Cannot change language / options

### ISSUE THREAD

**Issue by ghost** [AddonScriptorDE/plugin.video.southpark_de#2]
I hope this is not just me being stupid, but I can't find the settings for this add-on. I don't know how to change the audio to English.

I use 1.0.2 on raspbmc.

EDIT:

I found the settings in the global xbmc addon settings. Kind of strange that I can't access them from within the add-on though, you might want to add that.

**Comment by AddonScriptorDE** [comment]
You can access the settings, like in any other addon, via the context menu "Addon-Settings".
