### ISSUE TITLE
Preview der Videos läuft, aber beim Click auf ein Video kommt ein Scriptfehler

### ISSUE THREAD

**Issue by finishlast** [AddonScriptorDE/plugin.video.southpark_de#4]
Meine Frau guckt gerne Chefkoch.de und nun läuft es leider nicht mehr und ich bekomme nun keine gebrannten Mandeln...

Im Chefkochplugin kann man die einzelnen  Videos sehen, aber sobald man eins startet kommt ein Scriptfehler, habe XBMC Eden probiert, da kommt kein Scriptfehler, es passiert gar nichts, auf XBMC 12 RC2 kommt wie gesagt ein Pythonfehler.

Im Log steht 400 Bad Request.

Hab noch nicht ins Script geschaut, wollte ich aber noch, will mich ja weiterbilden...

Mist, hab's ins falsche Plugin gepostet...

**Comment by AddonScriptorDE** [comment]
Hi,
lustig :) Wegen dem "Chefkoch" ists nun im SouthPark Addon gelandet.
Hab das Chefkoch Addon mal gefixt. http://www.xbmcnerds.com/index.php?page=Thread&postID=89736#post89736
Ich packs die Tage dann auch ins Repo...
