### ISSUE TITLE
Option für Bitrate

### ISSUE THREAD

**Issue by Caeboox2** [AddonScriptorDE/plugin.video.southpark_de#5]
Das Addon nimmt standardmäßig die höchste verfügbare Bitrate. Bitte nicht lachen, aber ich habe nur eine 1MBit-Leitung und die wird gerade bei den neueren Folgen mit 720p leicht überlastet.

Ich habe mir mit einem kleinen unsauberen Fix geholfen, der immer die kleinste Bitrate wählt (default.py):

<pre><code>urlNew=""
# bitrate=0
bitrate=999999
...
for temp1,temp2,br,temp3,url in match:
# if int(br)&gt;bitrate:
if int(br)&lt;bitrate:
</code></pre>

Schön wäre eine Option, mit der man die höchste Bitrate festlegen kann. Falls es keine kleinere Bitrate gibt, sollte die nächstgrößere gewählt werden.

Ich könnte das selbst ohne Probleme sauber coden, habe aber noch keine Ahnung, wie das organisatorisch hier auf GitHub abläuft.

Also, falls Interesse an dieser Option besteht, baue ich sie gerne ordentlich ein.

Ein sehr schönes Addon, vielen Dank!

**Comment by Caeboox2** [comment]
Ich habe die Option nun richtig integriert. Keine Ahnung was ich jetzt tun soll um es vorzustellen.

**Comment by AddonScriptorDE** [comment]
Sorry für die späte Antwort. Hatte soviel zu tun und hab jetzt erst hier reingeschaut.
Ich bau die Option in die nächste Version ein.

Hatte das bisher nicht gemacht, da die Bitrate für 720p doch sehr gering ist. Aber gibt ja doch genug Leute mit ner langsamen iNet Verbindung... ;)
