### ISSUE TITLE
failed to open source

### ISSUE THREAD

**Issue by Deban** [AddonScriptorDE/plugin.video.southpark_de#8]
Seit ein paar Wochen lädt das Plugin keine Videos mehr. 
In der XBMC Log kann ich folgende Fehlermeldung finden:

ERROR: virtual bool XFILE::CFileCache::Open(const CURL&) - failed to open source http://mtvni.rd.llnwd.net/44620/cdnorigin/mtviestor/_!/intlod/southpark/video/Deutsche/Season_06/0609/acts/0609_1_DI_DEU_640x480_800.mp4

Kann es sein, das sich die Video URL geändert hat?

**Comment by Hypfer** [comment]
https://code.google.com/p/addonscriptorde-beta-repo/source/browse/#svn%2Ftrunk%2Fplugin.video.southpark_de

Da scheint es Abhilfe zu geben.

**Comment by Deban** [comment]
Super, vielen Dank für den Tipp. Mit dem Addon aus dem Testing Repository klappt das streamen der Folgen wieder problemlos.
